version: '3'
networks:
  proxy:
services:
  traefik:
      image: traefik
      restart: unless-stopped
      command: --api --docker
      networks:
        - proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.localhost"
        - "traefik.port=8080"
  tls-client:
    container_name: tls-client
    build:
      context: .
      args:
        - PKG=client
      dockerfile: ./Docker/Client.Dockerfile
    image:
      tlsclient:latest
    volumes:
      - ${GOPATH}/src/github.com/chrispaynes/goTLS/pkg:${GOPATH}/src/github.com/chrispaynes/goTLS/pkg
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.backend=client"
      - "traefik.frontend.rule=Host:tls.client.localhost"
      - "traefik.docker.network=proxy"
  tls-server:
    container_name: tls-server
    build:
      context: .
      args:
        - PKG=server
      dockerfile: ./Docker/Client.Dockerfile
    image:
      tlsserver:latest
    volumes:
      - ${GOPATH}/src/github.com/chrispaynes/goTLS/pkg:${GOPATH}/src/github.com/chrispaynes/goTLS/pkg
    restart: always
    networks:
      - proxy
    ports:
      - "3000:3000"
    labels:
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:tls.server.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=3000"

